### ISSUE TITLE
The process '/usr/bin/pwsh' failed with exit code 1

### ISSUE THREAD

**Issue by hillalcantarapwc** [Azure/Azure-Governance-Visualizer-Accelerator#15]
See attached error.

[error_AzGovViz.txt](https://github.com/Azure/Azure-Governance-Visualizer-Accelerator/files/14692857/error_AzGovViz.txt)

Also, got warning for deprecated code. This happened after running DeployAzGovViz.

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/powershell@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by hillalcantarapwc** [comment]
Found the issue. It seems this is only applicable when you have permission on the management group level. Can't this be applied on the subscription level?

**Comment by sebassem** [comment]
@hillalcantarapwc  Thanks for opening this issue, this has been fixed by #14 . Please fetch the latest code and try again.
