### ISSUE TITLE
Questions about wiki

### ISSUE THREAD

**Issue by neok-g** [Azure/Azure-Governance-Visualizer-Accelerator#16]
I am pretty new to the AzGovViz. I have some questions about the generated wiki:

- There is only a summary page generated with total numbers see first screenshot. However from there I cannot see for instance which policy assignments, policy definitions etc.. I only see the numbers.
- If I navigate through the Wiki menu all folders are empty see second screenshot
- However the corresponding wiki folder seems to be filled see third screenshot

Am I doing something wrong?

![image](https://github.com/Azure/Azure-Governance-Visualizer-Accelerator/assets/3228810/28e31462-3792-4784-93f9-7fcbddef480c)

![image](https://github.com/Azure/Azure-Governance-Visualizer-Accelerator/assets/3228810/eb6612d0-a071-4c1c-b844-7cb48b7dd8f9)

![image](https://github.com/Azure/Azure-Governance-Visualizer-Accelerator/assets/3228810/e62cf547-3656-454b-83a3-86cdadb40722)

**Comment by sebassem** [comment]
@JulianHayward can you advise on this one ?

**Comment by JulianHayward** [comment]
@neok-g there is one folder 'wiki' and then we have the ado wiki. In the ado wiki it will only render markdown (first screenshot) all other is noise (that should have been designed better at the azgvz project start to have a dedicated folder for the ado wiki md file(s).. but here we are :)). In the wiki folder you can find all the detailed outputs such as html, csv and json. Hope that helps..

@sebassem fyi

**Comment by sebassem** [comment]
Closing this issue, thanks @JulianHayward
