### ISSUE TITLE
Error You do not have permission to view this directory or page

### ISSUE THREAD

**Issue by jdeblaey** [Azure/Azure-Governance-Visualizer-Accelerator#22]
Hello,

I am trying to deploy this, and I followed the instructions and when I try to get to the site, I am getting a blank white page saying "You do not have permission to view this directory or page" even though I have granted myself and others' rights to the service principal that deals with the authentication.

Are there any suggestions of what I can try to do to resolve this?

Thanks,
Jim

**Comment by jdeblaey** [comment]
for added context it is stopping at the https://{your-web-app-name}.azurewebsites.net/.auth/login/aad/callback that is where it is stating I do not have permission

**Comment by IgnacioKaplan** [comment]
I have the same issue, can you please let me know what was the solution to this problem please?
