### ISSUE TITLE
On Checking prerequisits

### ISSUE THREAD

**Issue by Ashley72** [Azure/Azure-Governance-Visualizer-Accelerator#8]
When running DeployAzGovViz section I get the following error msg
Initializing Az Module Complete
Running Az PowerShell Script
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command /home/runner/work/_temp/ca514f13-cd11-4a71-bf5c-34ed2b880d6d.ps1
CodeRunPlatform: GitHubActions
Testing if repository 'https://github.com/Ashley72/AzGovViz' is accessible from the public
Test returned statusCode: '200' - 'https://github.com/Ashley72/AzGovViz' is accessible from the public!
Assuming and insisting that you do not want to publish your tenant insights to the public - throw
Exception: /home/runner/work/AzGovViz/AzGovViz/pwsh/prerequisites.ps1:39
Line |
  39 |              throw
     |              ~~~~~
     | ScriptHalted

Error: Error: The process '/usr/bin/pwsh' failed with exit code 1

**Comment by sebassem** [comment]
Hi @Ashley72  you need to set your repository to be private for the rest of the setup to proceed
