### ISSUE TITLE
Error running DeployAzGovViz workflow

### ISSUE THREAD

**Issue by jerrolmossel** [Azure/Azure-Governance-Visualizer-Accelerator#9]
Hi,

I'm getting an error when running workflow 'DeployAzGovViz' from Github actions.
Any idea what goes wrong? 

Step within workflow: Run Azure Governance Visualizer

Output/Files will be created in path '/home/runner/work/Azure-Governance-Visualizer/Azure-Governance-Visualizer/wiki/.'
 Verify 'AzAPICall' (1.1.78)
Get-Package: No match was found for the specified search criteria and module names
'AzAPICall'.

Exception: /home/runner/work/Azure-Governance-Visualizer/Azure-Governance-Visualizer/pwsh/AzGovVizParallel.ps1:29025
 Line |
29025 |              Throw 'Error - Azure Governance Visualizer: check the las …
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Error - Azure Governance Visualizer: check the last console output for
      | details

Error: Error: The process '/usr/bin/pwsh' failed with exit code 1

**Comment by sebassem** [comment]
@jerrolmossel  thanks for submitting this issue, can you share the full error in the workflow run? This is probably has failed due to one of the checks that AzGovViz deployment performs has not passed

**Comment by jerrolmossel** [comment]
Run azure/powershell@v1
Validating inputs
Module Az latest installed from hostedAgentFolder
Initializing Az Module
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command Test-Path (Join-Path /usr/share az_*)
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command try {
            $ErrorActionPreference = "Stop"
            $WarningPreference = "SilentlyContinue"
            $output = @{}
            $data = Get-Module -Name Az -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
            $output['AzVersion'] = $data.Version.ToString()
            $output['Success'] = "true"
        }
        catch {
            $output['Error'] = $_.exception.Message
        }
        return ConvertTo-Json $output
True
{
  "AzVersion": "9.3.0",
  "Success": "true"
}
Initializing Az Module Complete
Running Az PowerShell Script
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command /home/runner/work/_temp/e7ead805-5839-48b7-a9d6-84958dfad74a.ps1
Start Azure Governance Visualizer 28-Sep-2023 09:20:40 (#6.3.1)
Checking PowerShell edition and version
  PS check passed : (Major[7]; Minor[2] gt 0); (minimum supported version '7.0.3')
  PS Edition: Core; PS Version: 7.2.14
  PS Version check succeeded
Output/Files will be created in path '/home/runner/work/Azure-Governance-Visualizer/Azure-Governance-Visualizer/wiki/.'
 Verify 'AzAPICall' (1.1.78)
Get-Package: No match was found for the specified search criteria and module names
'AzAPICall'.

  AzAPICall - Deviating module version 
  'AzAPICall 1.1.78' not installed
  Installing AzAPICall module (1.1.78)
Initialize 'AzAPICall'
 AzAPICall 1.1.78
 Check required Az modules cmdlets
  Az PS module supporting cmdlet 'Get-AzContext' installed
  Az Module Az.Accounts Version: could not be assessed
  Required Az modules cmdlets check succeeded
 Create htParameters
  codeRunPlatform: GitHubActions
  AzAPICall debug disabled
  AzAPICall htParameters:

Name                         Value
----                         -----
gitHubRepository             aka.ms/AzGovViz
writeMethod                  Host
onGitHubActions              True
onAzureDevOpsOrGitHubActions True
azAccountsVersion            n/a
azAPICallModuleVersion       1.1.78
psVersion                    7.2.14
onAzureDevOps                False
codeRunPlatform              GitHubActions
debugAzAPICall               False
debugWriteMethod             Host


  Create htParameters succeeded
 Get Az context
  Get Az context succeeded
 Set environment endPoint url mapping
  Check endpoint: 'ARM'; endpoint url: 'https://management.azure.com/'
  Check endpoint: 'KeyVault'; endpoint url: 'https://vault.azure.net'
  Check endpoint: 'LogAnalytics'; endpoint url: 'https://api.loganalytics.io'
  Check endpoint: 'MicrosoftGraph'; endpoint url: 'https://graph.microsoft.com'
  Check endpoint: 'Login'; endpoint url: 'https://login.microsoftonline.com'
  Check endpoint: 'Storage'; endpoint url: 'core.windows.net'
  Add to endpoint: 'Storage'; endpoint url: 'storage.azure.net'
  Set endpoint: 'Kusto'; endpoint url: 'kusto.windows.net'
  Set environment endPoint url mapping succeeded
 Check Az context
  Az context AccountId: '***'
  Az context AccountType: 'ClientAssertion'
  Az context related parameters: -SubscriptionId4AzContext=='***'; -TenantId4AzContext=='undefined'; -SkipAzContextSubscriptionValidation=='False'
  Az context is already set to SubscriptionId: '***'
  Check Subscription: '***' (criteria: quotaId notLike 'AAD*'; state==enabled)
 +Processing new bearer token request 'ARM' "https://management.azure.com"
 +*** 'ARM': [tokenRequestProcessed: '09/28/2023 09:20:54']; [expiryDateTime: '09/28/2023 10:20:54']; [timeUntilExpiry: '00:59:59.5631912']
   Subscription check succeeded - quotaId: 'EnterpriseAgreement_2014-09-01'; state: Enabled
  Stay with current Az context: Tenant:'***' Subscription:'dc-mgt-01 (***)'
   Az context Tenant: '***'
   Az context Subscription: 'dc-mgt-01 (***)' (state: Enabled)
  Az context check succeeded
  Get ARM locations
   Get ARM locations succeeded (locations count: '83')
 Initialize 'AzAPICall' succeeded
AzAPICall module version requirement check succeeded: 1.1.78 or greater - current: 1.1.78 
Azure Governance Visualizer version is up to date '6.3.1'
Environment: AzureCloud
Add Azure Governance Visualizer htParameters
htParameters:

Name                                         Value
----                                         -----
RBACAtScopeOnly                              False
NoResourceProvidersDetailed                  False
HierarchyMapOnly                             False
subscriptionQuotaId                          EnterpriseAgreement_2014-09-01
NoJsonExport                                 False
GitHubActionsOIDC                            True
NoResources                                  False
ProductVersion                               6.3.1
debugAzAPICall                               False
DoNotShowRoleAssignmentsUserData             False
DoPSRule                                     False
ThrottleLimit                                10
DoNotIncludeResourceGroupsOnPolicy           False
azAccountsVersion                            n/a
debugWriteMethod                             Host
LargeTenant                                  False
gitHubRepository                             aka.ms/AzGovViz
accountType                                  ClientAssertion
DoAzureConsumption                           False
NoStorageAccountAccessAnalysis               False
psVersion                                    7.2.14
DoNotIncludeResourceGroupsAndResourcesOnRBAC False
ARMLocations                                 {eastus, eastus2, southcentralus, westus2…}
onAzureDevOpsOrGitHubActions                 True
onGitHubActions                              True
azAPICallModuleVersion                       1.1.78
PolicyAtScopeOnly                            False
onAzureDevOps                                False
NoNetwork                                    False
writeMethod                                  Host
ManagementGroupsOnly                         False
NoPolicyComplianceStates                     False
PSRuleFailedOnly                             False
NoResourceProvidersAtAll                     False
NoALZPolicyVersionChecker                    False
userType                                     n/a
codeRunPlatform                              GitHubActions
NoMDfCSecureScore                            False


Add Azure Governance Visualizer htParameters succeeded
Checking ClientAssertion permissions
 +Processing new bearer token request 'MicrosoftGraph' "https://graph.microsoft.com"
 +*** 'MicrosoftGraph': [tokenRequestProcessed: '09/28/2023 09:[21](https://github.com/thuas-itops/Azure-Governance-Visualizer/actions/runs/6336976052/job/17211103123#step:5:22):00']; [expiryDateTime: '09/28/20[23](https://github.com/thuas-itops/Azure-Governance-Visualizer/actions/runs/6336976052/job/17211103123#step:5:24) 10:21:00']; [timeUntilExpiry: '00:59:59.4494448']
[AzAPICallErrorHandler 1.1.78] Test MSGraph PrivilegedAccess.Read.AzureResources permission try #1; return: (StatusCode: '400' (BadRequest)) <.code: ''> <.error.code: 'AadPremiumLicenseRequired'> | <.message: ''> <.error.message: 'The tenant needs an AAD Premium 2 license.'> - AzAPICall: return 'failed'
Checking permissions for ManagementGroup '***'
Permission check results
MSGraph API 'Users Read' permission - check PASSED
MSGraph API 'Groups Read' permission - check PASSED
MSGraph API 'ServicePrincipals Read' permission - check PASSED
MSGraph API 'PrivilegedAccess.Read.AzureResources' permission - check FAILED - if you cannot grant this permission or you do not have an AAD Premium 2 license then use parameter -NoPIMEligibility
RBAC 'Reader' permissions on Management Group '***' - check PASSED
Please consult the documentation for permission requirements: https://aka.ms/AzGovViz#technical-documentation
Exception: /home/runner/work/Azure-Governance-Visualizer/Azure-Governance-Visualizer/pwsh/AzGovVizParallel.ps1:290[25](https://github.com/thuas-itops/Azure-Governance-Visualizer/actions/runs/6336976052/job/17211103123#step:5:26)
 Line |
[29](https://github.com/thuas-itops/Azure-Governance-Visualizer/actions/runs/6336976052/job/17211103123#step:5:30)025 |              Throw 'Error - Azure Governance Visualizer: check the las …
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Error - Azure Governance Visualizer: check the last console output for
      | details

Error: Error: The process '/usr/bin/pwsh' failed with exit code 1

**Comment by sebassem** [comment]
The error is due to not having P2 license, you need to provide the -NoPIMEligibility switch as indicated in the example [here](https://github.com/Azure/Azure-Governance-Visualizer-Accelerator#how-to-deploy)

**Comment by jerrolmossel** [comment]
Thanks, it works now but I still get the error messages in my first comment.

Other then that is works fine. Getting a succesfull workflow run and the output is pushed to the webapp.

![image](https://github.com/Azure/Azure-Governance-Visualizer-Accelerator/assets/51243261/95dd785d-830e-4969-963f-3b34be3505dc)

**Comment by sebassem** [comment]
Great to hear it works. This error is something you can ignore.
